// src/constants/storeCategories.ts
export const STORE_CATEGORIES = [
  "Grocery",
  "Restaurant",
  "Pharmacy",
  "Electronics",
  "Clothing",
  "Furniture",
  "Bakery",
  "Butcher",
  "Fish Market",
  "Dairy",
  "Stationery",
  "Hardware",
  "Mobile Shop",
  "Salon",
  "Gym",
  "Laundry",
  "Tailor",
  "Shoe Store",
  "Jewelry",
  "Books",
  "Toys",
  "Gifts",
  "Flowers",
  "Pet Store",
  "Auto Parts",
  "Other",
];

export const SERVICE_CATEGORIES = [
  "Delivery",
  "Same Day Delivery",
  "Express Delivery",
  "Bulk Orders",
  "Rental",
  "Vehicle Rental",
  "Equipment Rental",
  "Saloon & Beauty",
  "Hair Cutting",
  "Beauty Services",
  "Makeup",
  "Welding",
  "Metal Fabrication",
  "Tailoring",
  "Clothes Stitching",
  "Alterations",
  "Plumbing",
  "Electrical",
  "Home Repairs",
  "Carpentry",
  "Painting",
  "Cleaning",
  "Laundry",
  "Dry Cleaning",
  "Pest Control",
  "AC Repair",
  "Appliance Repair",
  "Photography",
  "Event Services",
  "Catering",
  "Transportation",
  "Moving Services",
  "Courier",
  "Printing",
  "Other",
];

export const BUSINESS_TYPES = [
  { id: "products", label: "Products", description: "Sell physical products" },
  { id: "services", label: "Services", description: "Offer services" },
  { id: "both", label: "Both", description: "Products & Services" },
];
