export type CategoryOption = {
  id: string;
  name: string;
  icon: string;
  color: string;
};

export const STORE_TYPES = [
  "Grocery",
  "Medical",
  "Tailor",
  "Mechanical",
  "Property",
  "Phone",
  "Photo",
  "Makeup",
  "Book Depot",
  "Electric",
  "Welding",
  "Chicken",
  "Pizza",
  "Bag",
  "Light",
  "Sabji",
  "Clothes",
  "Specs",
  "Sari",
  "Carpet",
  "Paint",
  "Glass",
  "Shoes",
  "Charpi",
  "Mandir",
  "Furniture",
  "Motor",
  "Band",
  "Repair",
  "ATM",
  "Fish",
  "Garden",
  "Tyre",
  "Pan",
  "Sewing Machine",
  "Dhaba",
  "Teeth",
  "Cosmetic",
  "Travel",
  "Milk",
  "Parking",
  "Steel",
  "Car Wash",
  "Toy",
  "Battery",
  "Saloon",
  "Car Repair",
  "Gold/Silver",
  "Gym",
] as const;

export const PRODUCT_CATEGORIES: CategoryOption[] = [
  { id: "all", name: "All", icon: "🛒", color: "#6366f1" },
  { id: "vegetables", name: "Vegetables", icon: "🥬", color: "#4ade80" },
  { id: "fruits", name: "Fruits", icon: "🍎", color: "#fb923c" },
  { id: "dairy", name: "Dairy", icon: "🥛", color: "#60a5fa" },
  { id: "grocery", name: "Grocery", icon: "🛍️", color: "#16a34a" },
  { id: "bakery", name: "Bakery", icon: "🍞", color: "#a78bfa" },
  { id: "meat", name: "Meat & Fish", icon: "🍗", color: "#f87171" },
  { id: "snacks", name: "Snacks", icon: "🍿", color: "#fbbf24" },
  { id: "beverages", name: "Beverages", icon: "🥤", color: "#f472b6" },
  { id: "electronics", name: "Electronics", icon: "📱", color: "#3b82f6" },
  { id: "garments", name: "Garments", icon: "👕", color: "#8b5cf6" },
  { id: "shoes", name: "Shoes", icon: "👟", color: "#78716c" },
  { id: "furniture", name: "Furniture", icon: "🪑", color: "#92400e" },
  { id: "home decor", name: "Home Decor", icon: "🏠", color: "#14b8a6" },
  { id: "medical", name: "Medical", icon: "💊", color: "#dc2626" },
  { id: "beauty", name: "Beauty", icon: "💄", color: "#db2777" },
  { id: "salon", name: "Salon", icon: "💇", color: "#f97316" },
  { id: "stationery", name: "Stationery", icon: "📝", color: "#f59e0b" },
  { id: "toys", name: "Toys", icon: "🧸", color: "#10b981" },
  { id: "jewelry", name: "Jewelry", icon: "💍", color: "#eab308" },
  { id: "gym equipment", name: "Gym Equipment", icon: "🏋️", color: "#7c3aed" },
  { id: "sports", name: "Sports", icon: "⚽", color: "#059669" },
  { id: "pet supplies", name: "Pet Supplies", icon: "🐾", color: "#d97706" },
  { id: "garden", name: "Garden", icon: "🌱", color: "#22c55e" },
  { id: "automotive", name: "Automotive", icon: "🚗", color: "#475569" },
  { id: "hardware", name: "Hardware", icon: "🔨", color: "#b45309" },
  { id: "carpenter", name: "Carpenter", icon: "🪵", color: "#a16207" },
  { id: "architecture", name: "Architecture", icon: "🏗️", color: "#475569" },
  { id: "books", name: "Books", icon: "📚", color: "#6d28d9" },
  { id: "mobile accessories", name: "Mobile Accessories", icon: "🎧", color: "#0891b2" },
  { id: "kitchen", name: "Kitchen", icon: "🍳", color: "#ea580c" },
  { id: "sweets", name: "Sweets & Mithai", icon: "🍬", color: "#e11d48" },
  { id: "paan", name: "Paan & Supari", icon: "🌿", color: "#15803d" },
  { id: "pooja", name: "Pooja Items", icon: "🪔", color: "#ca8a04" },
  { id: "others", name: "Others", icon: "📦", color: "#94a3b8" },
];

export const SERVICE_CATEGORY_IDS = ["salon", "carpenter", "architecture"] as const;

export const SERVICE_CATEGORIES: CategoryOption[] = [
  { id: "all", name: "All", icon: "🔧", color: "#6366f1" },
  { id: "saloon & beauty", name: "Saloon & Beauty", icon: "💇", color: "#ec4899" },
  { id: "hair cutting", name: "Hair Cutting", icon: "✂️", color: "#f97316" },
  { id: "beauty services", name: "Beauty Services", icon: "💄", color: "#db2777" },
  { id: "makeup", name: "Makeup", icon: "💅", color: "#f472b6" },
  { id: "gym", name: "Gym & Fitness", icon: "🏋️", color: "#7c3aed" },
  { id: "yoga", name: "Yoga", icon: "🧘", color: "#14b8a6" },
  { id: "bowling", name: "Bowling", icon: "🎳", color: "#3b82f6" },
  { id: "pool", name: "Swimming Pool", icon: "🏊", color: "#0ea5e9" },
  { id: "spa", name: "Spa & Massage", icon: "💆", color: "#a855f7" },
  { id: "coaching", name: "Coaching & Tuition", icon: "📖", color: "#6d28d9" },
  { id: "dance", name: "Dance Classes", icon: "💃", color: "#e11d48" },
  { id: "music", name: "Music Classes", icon: "🎵", color: "#8b5cf6" },
  { id: "delivery", name: "Delivery", icon: "🚚", color: "#3b82f6" },
  { id: "welding", name: "Welding", icon: "⚙️", color: "#78716c" },
  { id: "tailoring", name: "Tailoring", icon: "🧵", color: "#8b5cf6" },
  { id: "plumbing", name: "Plumbing", icon: "🔩", color: "#0ea5e9" },
  { id: "electrical", name: "Electrical", icon: "⚡", color: "#eab308" },
  { id: "carpentry", name: "Carpentry", icon: "🪵", color: "#a16207" },
  { id: "painting", name: "Painting", icon: "🎨", color: "#14b8a6" },
  { id: "cleaning", name: "Cleaning", icon: "🧹", color: "#22c55e" },
  { id: "laundry", name: "Laundry", icon: "👔", color: "#6366f1" },
  { id: "ac repair", name: "AC Repair", icon: "❄️", color: "#38bdf8" },
  { id: "photography", name: "Photography", icon: "📷", color: "#a855f7" },
  { id: "catering", name: "Catering", icon: "🍽️", color: "#f59e0b" },
  { id: "transportation", name: "Transportation", icon: "🚗", color: "#64748b" },
  { id: "home repairs", name: "Home Repairs", icon: "🏠", color: "#10b981" },
  { id: "car wash", name: "Car Wash", icon: "🚿", color: "#06b6d4" },
  { id: "pest control", name: "Pest Control", icon: "🐛", color: "#84cc16" },
  { id: "security", name: "Security", icon: "🛡️", color: "#64748b" },
  { id: "event planning", name: "Event Planning", icon: "🎉", color: "#f43f5e" },
  { id: "medical", name: "Medical Services", icon: "🏥", color: "#dc2626" },
  { id: "others", name: "Others", icon: "📦", color: "#94a3b8" },
];
