// src/assets/mockData.ts
import { Reel } from "../context/AppContext";
export interface Store {
  id: string;
  name: string;
  type: string;
  followers: string;
  rating: number;
  distance: string;
  image: string; // Main image for backward compatibility
  images?: string[]; // Multiple images (up to 5) for carousel
}

export const mockStores: Store[] = [
  {
    id: "1",
    name: "Organic Farms",
    type: "Grocery",
    followers: "1.2k",
    rating: 4.8,
    distance: "0.4 km",
    image: "https://picsum.photos/seed/shop1/400/300",
    images: [
      "https://picsum.photos/seed/shop1/400/300",
      "https://picsum.photos/seed/shop1a/400/300",
      "https://picsum.photos/seed/shop1b/400/300",
      "https://picsum.photos/seed/shop1c/400/300",
    ],
  },
  {
    id: "2",
    name: "LifeCare Pharma",
    type: "Medical",
    followers: "850",
    rating: 4.5,
    distance: "0.8 km",
    image: "https://picsum.photos/seed/shop2/400/300",
    images: [
      "https://picsum.photos/seed/shop2/400/300",
      "https://picsum.photos/seed/shop2a/400/300",
      "https://picsum.photos/seed/shop2b/400/300",
    ],
  },
  {
    id: "3",
    name: "Stitch & Style",
    type: "Tailor",
    followers: "500",
    rating: 4.2,
    distance: "1.1 km",
    image: "https://picsum.photos/seed/shop3/400/300",
    images: [
      "https://picsum.photos/seed/shop3/400/300",
      "https://picsum.photos/seed/shop3a/400/300",
      "https://picsum.photos/seed/shop3b/400/300",
      "https://picsum.photos/seed/shop3c/400/300",
      "https://picsum.photos/seed/shop3d/400/300",
    ],
  },
  {
    id: "4",
    name: "Pizza Palace",
    type: "Pizza",
    followers: "2.5k",
    rating: 4.9,
    distance: "0.3 km",
    image: "https://picsum.photos/seed/shop4/400/300",
    images: [
      "https://picsum.photos/seed/shop4/400/300",
      "https://picsum.photos/seed/shop4a/400/300",
      "https://picsum.photos/seed/shop4b/400/300",
    ],
  },
  {
    id: "5",
    name: "Auto Masters",
    type: "Mechanical",
    followers: "1.1k",
    rating: 4.6,
    distance: "2.5 km",
    image: "https://picsum.photos/seed/shop5/400/300",
    images: [
      "https://picsum.photos/seed/shop5/400/300",
      "https://picsum.photos/seed/shop5a/400/300",
      "https://picsum.photos/seed/shop5b/400/300",
      "https://picsum.photos/seed/shop5c/400/300",
    ],
  },
  {
    id: "6",
    name: "Glow Up Studio",
    type: "Makeup",
    followers: "3.2k",
    rating: 4.7,
    distance: "0.6 km",
    image: "https://picsum.photos/seed/shop6/400/300",
    images: [
      "https://picsum.photos/seed/shop6/400/300",
      "https://picsum.photos/seed/shop6a/400/300",
      "https://picsum.photos/seed/shop6b/400/300",
      "https://picsum.photos/seed/shop6c/400/300",
    ],
  },
  {
    id: "7",
    name: "The Book Nook",
    type: "Book Depot",
    followers: "900",
    rating: 4.4,
    distance: "1.5 km",
    image: "https://picsum.photos/seed/shop7/400/300",
    images: [
      "https://picsum.photos/seed/shop7/400/300",
      "https://picsum.photos/seed/shop7a/400/300",
      "https://picsum.photos/seed/shop7b/400/300",
    ],
  },
  {
    id: "8",
    name: "Fresh Greens",
    type: "Sabji",
    followers: "1.5k",
    rating: 4.3,
    distance: "0.2 km",
    image: "https://picsum.photos/seed/shop8/400/300",
    images: [
      "https://picsum.photos/seed/shop8/400/300",
      "https://picsum.photos/seed/shop8a/400/300",
      "https://picsum.photos/seed/shop8b/400/300",
      "https://picsum.photos/seed/shop8c/400/300",
    ],
  },
  {
    id: "9",
    name: "Iron & Fire",
    type: "Welding",
    followers: "300",
    rating: 4.0,
    distance: "3.2 km",
    image: "https://picsum.photos/seed/shop9/400/300",
    images: [
      "https://picsum.photos/seed/shop9/400/300",
      "https://picsum.photos/seed/shop9a/400/300",
      "https://picsum.photos/seed/shop9b/400/300",
    ],
  },
  {
    id: "10",
    name: "Royal Furniture",
    type: "Furniture",
    followers: "2.1k",
    rating: 4.8,
    distance: "2.1 km",
    image: "https://picsum.photos/seed/shop10/400/300",
    images: [
      "https://picsum.photos/seed/shop10/400/300",
      "https://picsum.photos/seed/shop10a/400/300",
      "https://picsum.photos/seed/shop10b/400/300",
      "https://picsum.photos/seed/shop10c/400/300",
      "https://picsum.photos/seed/shop10d/400/300",
    ],
  },
  {
    id: "11",
    name: "Modern Sari House",
    type: "Sari",
    followers: "4.5k",
    rating: 4.9,
    distance: "0.9 km",
    image: "https://picsum.photos/seed/shop11/400/300",
    images: [
      "https://picsum.photos/seed/shop11/400/300",
      "https://picsum.photos/seed/shop11a/400/300",
      "https://picsum.photos/seed/shop11b/400/300",
      "https://picsum.photos/seed/shop11c/400/300",
    ],
  },
  {
    id: "12",
    name: "Petal Pushers",
    type: "Garden",
    followers: "1.2k",
    rating: 4.6,
    distance: "1.8 km",
    image: "https://picsum.photos/seed/shop12/400/300",
    images: [
      "https://picsum.photos/seed/shop12/400/300",
      "https://picsum.photos/seed/shop12a/400/300",
      "https://picsum.photos/seed/shop12b/400/300",
    ],
  },
  {
    id: "13",
    name: "The Gym Box",
    type: "Gym",
    followers: "5.6k",
    rating: 4.7,
    distance: "0.5 km",
    image: "https://picsum.photos/seed/shop13/400/300",
    images: [
      "https://picsum.photos/seed/shop13/400/300",
      "https://picsum.photos/seed/shop13a/400/300",
      "https://picsum.photos/seed/shop13b/400/300",
      "https://picsum.photos/seed/shop13c/400/300",
    ],
  },
  {
    id: "14",
    name: "City Car Wash",
    type: "Car Wash",
    followers: "700",
    rating: 4.3,
    distance: "2.8 km",
    image: "https://picsum.photos/seed/shop14/400/300",
    images: [
      "https://picsum.photos/seed/shop14/400/300",
      "https://picsum.photos/seed/shop14a/400/300",
      "https://picsum.photos/seed/shop14b/400/300",
    ],
  },
  {
    id: "15",
    name: "Dhaba Express",
    type: "Dhaba",
    followers: "3.8k",
    rating: 4.5,
    distance: "4.2 km",
    image: "https://picsum.photos/seed/shop15/400/300",
    images: [
      "https://picsum.photos/seed/shop15/400/300",
      "https://picsum.photos/seed/shop15a/400/300",
      "https://picsum.photos/seed/shop15b/400/300",
      "https://picsum.photos/seed/shop15c/400/300",
    ],
  },
  {
    id: "16",
    name: "Vision Optics",
    type: "Specs",
    followers: "1.4k",
    rating: 4.4,
    distance: "1.2 km",
    image: "https://picsum.photos/seed/shop16/400/300",
    images: [
      "https://picsum.photos/seed/shop16/400/300",
      "https://picsum.photos/seed/shop16a/400/300",
      "https://picsum.photos/seed/shop16b/400/300",
    ],
  },
  {
    id: "17",
    name: "Toy World",
    type: "Toy",
    followers: "2.2k",
    rating: 4.7,
    distance: "1.6 km",
    image: "https://picsum.photos/seed/shop17/400/300",
    images: [
      "https://picsum.photos/seed/shop17/400/300",
      "https://picsum.photos/seed/shop17a/400/300",
      "https://picsum.photos/seed/shop17b/400/300",
      "https://picsum.photos/seed/shop17c/400/300",
    ],
  },
  {
    id: "18",
    name: "Glitters Gold",
    type: "Gold/Silver",
    followers: "8.2k",
    rating: 5.0,
    distance: "0.7 km",
    image: "https://picsum.photos/seed/shop18/400/300",
    images: [
      "https://picsum.photos/seed/shop18/400/300",
      "https://picsum.photos/seed/shop18a/400/300",
      "https://picsum.photos/seed/shop18b/400/300",
      "https://picsum.photos/seed/shop18c/400/300",
    ],
  },
  {
    id: "19",
    name: "Travel Tunes",
    type: "Travel",
    followers: "1.1k",
    rating: 4.1,
    distance: "2.3 km",
    image: "https://picsum.photos/seed/shop19/400/300",
    images: [
      "https://picsum.photos/seed/shop19/400/300",
      "https://picsum.photos/seed/shop19a/400/300",
      "https://picsum.photos/seed/shop19b/400/300",
    ],
  },
  {
    id: "20",
    name: "Daily Dairy",
    type: "Milk",
    followers: "1.9k",
    rating: 4.6,
    distance: "0.3 km",
    image: "https://picsum.photos/seed/shop20/400/300",
    images: [
      "https://picsum.photos/seed/shop20/400/300",
      "https://picsum.photos/seed/shop20a/400/300",
      "https://picsum.photos/seed/shop20b/400/300",
      "https://picsum.photos/seed/shop20c/400/300",
    ],
  },
];

export const STORE_TYPES = [
  "Grocery",
  "Medical",
  "Tailor",
  "Mechanical",
  "Property",
  "Phone",
  "Photo",
  "Makeup",
  "Book Depot",
  "Electric",
  "Welding",
  "Chicken",
  "Pizza",
  "Bag",
  "Light",
  "Sabji",
  "Clothes",
  "Specs",
  "Sari",
  "Carpet",
  "Paint",
  "Glass",
  "Shoes",
  "Charpi",
  "Mandir",
  "Furniture",
  "Motor",
  "Band",
  "Repair",
  "ATM",
  "Fish",
  "Garden",
  "Tyre",
  "Pan",
  "Sewing Machine",
  "Dhaba",
  "Teeth",
  "Cosmetic",
  "Travel",
  "Milk",
  "Parking",
  "Steel",
  "Car Wash",
  "Toy",
  "Battery",
  "Saloon",
  "Car Repair",
  "Gold/Silver",
  "Gym",
];

export const mockReels: Reel[] = [
  {
    _id: "1",
    videoUrl: "https://media.w3.org/2010/05/sintel/trailer.mp4",
    description:
      "Fresh organic veggies arrived at Green Store! 🥦 #SangamDeals",
    likesCount: 120,
    liked: false,
    user: {
      name: "Green Grocery Store",
      avatar: "https://i.pravatar.cc/150?u=green",
    },
    comments: [
      {
        user: { name: "Rahul", avatar: "" },
        text: "The tomatoes were very fresh!",
        isReview: true,
      },
      {
        user: { name: "Sita", avatar: "" },
        text: "Do you have avocados?",
        isReview: false,
      },
    ],
  },
  {
    _id: "2",
    videoUrl:
      "https://commondatastorage.googleapis.com/gtv-videos-library/sample/ForBiggerBlazes.mp4",
    description:
      "Exclusive fashion collection drops tonight! 👗 Don't miss out #StyleHub",
    likesCount: 340,
    liked: false,
    user: {
      name: "Fashion Forward",
      avatar: "https://i.pravatar.cc/150?u=fashion",
    },
    comments: [
      {
        user: { name: "Priya", avatar: "" },
        text: "Love these designs!",
        isReview: true,
      },
    ],
  },
  {
    _id: "3",
    videoUrl:
      "https://commondatastorage.googleapis.com/gtv-videos-library/sample/ForBiggerJoyrides.mp4",
    description:
      "Hot deals on kitchen appliances ⚡ Limited stock available #MustBuy",
    likesCount: 215,
    liked: false,
    user: {
      name: "TechHub Store",
      avatar: "https://i.pravatar.cc/150?u=tech",
    },
    comments: [
      {
        user: { name: "Amit", avatar: "" },
        text: "Great prices!",
        isReview: true,
      },
    ],
  },
  {
    _id: "4",
    videoUrl:
      "https://commondatastorage.googleapis.com/gtv-videos-library/sample/ElephantsDream.mp4",
    description:
      "New beauty and skincare products ✨ Get 30% off on first order #GlowUp",
    likesCount: 450,
    liked: false,
    user: {
      name: "Beauty Bliss",
      avatar: "https://i.pravatar.cc/150?u=beauty",
    },
    comments: [
      {
        user: { name: "Neha", avatar: "" },
        text: "Amazing quality products!",
        isReview: true,
      },
    ],
  },
  {
    _id: "5",
    videoUrl: "https://media.w3.org/2010/05/sintel/trailer.mp4",
    description:
      "Premium coffee beans just arrived ☕ Perfect for coffee lovers #CoffeeAddict",
    likesCount: 180,
    liked: false,
    user: {
      name: "Coffee Corner",
      avatar: "https://i.pravatar.cc/150?u=coffee",
    },
    comments: [
      {
        user: { name: "Raj", avatar: "" },
        text: "Best coffee in town!",
        isReview: true,
      },
    ],
  },
];
